routes/web.php
<?php

Route::group(
    [
        'prefix'     => 'two-factor-auth',
        'as'         => 'two-factor-auth.',
        'namespace'  => 'Way2Web\TwoFactorAuth\Http\Controllers\Web',
        'middleware' => ['web'],
    ],
    function () {
        Route::get('secret', [
            'as'   => 'secret.create',
            'uses' => 'SecretController@create',
        ]);

        Route::post('secret', [
            'as'         => 'secret.store',
            'uses'       => 'SecretController@store',
            'middleware' => ['throttle:50'],
        ]);

        Route::get('secret/edit', [
            'as'   => 'secret.edit',
            'uses' => 'SecretController@edit',
        ]);

        Route::post('secret/delete', [
            'as'   => 'secret.delete',
            'uses' => 'SecretController@delete',
        ]);

        Route::get('one-time-password', [
            'as'   => 'one-time-password.form',
            'uses' => 'AuthController@show',
        ]);

        Route::post('one-time-password', [
            'as'         => 'one-time-password.post',
            'uses'       => 'AuthController@verify',
            'middleware' => ['throttle:50'],
        ]);

        Route::get('status', [
            'as'         => 'status',
            'uses'       => 'AuthController@status',
            'middleware' => ['throttle:50'],
        ]);

        Route::get('status', [
            'as'         => 'status',
            'uses'       => 'AuthController@status',
            'middleware' => ['throttle:15'],
        ]);
    }
);

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ Lang::locale() }}" class="js-language">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title') - {{ config('app.name') }}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
</head>
<body>
<div>
    <main class="container">

        @yield('content')

    </main>
</div>
</body>
</html>

resources/views/secret/create.blade.php
@extends('two-factor-auth::layout')

@section('title', trans('two-factor-auth::secret-create.title'))

@section('content')
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <header class="text-center">
                <h1>{{ trans('two-factor-auth::secret-create.heading') }}</h1>
            </header>


            <form method="POST" action="{{ route('two-factor-auth.secret.store') }}" id="two-factor-auth-secret-store">
                @csrf


                <div class="text-center">
                    <p>{{ trans('two-factor-auth::secret-create.description', ['secret' => $secret]) }}</p>

                    <div>
                        <input type="hidden" value="{{ $secret }}" name="two_factor_auth_secret">
                        <img src="{{ $qrImageUrl }}" alt="QR Code">
                    </div>

                    <div class="text-center">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="{{ trans('two-factor-auth::secret-create.one-time-password-placeholder') }}" name="one_time_password" autofocus autocomplete="off">
                            @if($errors->has('one_time_password'))
                                <div class="alert alert-danger">
                                    {{ $errors->first('one_time_password') }}
                                </div>
                            @endif
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-block btn-primary">
                    {{ trans('two-factor-auth::secret-create.save') }}
                </button>

            </form>
        </div>
    </div>
@endsection

resources/views/secret/edit.blade.php
@extends('two-factor-auth::layout')

@section('title', trans('two-factor-auth::secret-edit.title'))

@section('content')
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <header class="text-center">
                <h1>{{ trans('two-factor-auth::secret-edit.heading') }}</h1>
            </header>

            <div class="text-center">
                <p>{{ trans('two-factor-auth::secret-edit.description') }}</p>
            </div>

            <form action="{{ route('two-factor-auth.secret.delete') }}" method="post">
                @method('delete')
                @csrf

                @if($errors->has('one_time_password'))
                    <div class="alert alert-danger">
                        {{ $errors->first('one_time_password') }}
                    </div>
                @endif

                <div class="text-center">
                    <div class="form-group">
                        <label for="one_time_password">Code</label>
                        <input id="one_time_password" type="text" name="one_time_password" class="form-control" placeholder="code" autofocus autocomplete="off">
                    </div>
                </div>

                <button type="submit" class="btn btn-block btn-primary">
                    {{ trans('two-factor-auth::secret-edit.action-delete') }}
                </button>
            </form>

        </div>
    </div>
@endsection

resources/views/secret/otp-form.blade.php
@extends('two-factor-auth::layout')

@section('title', trans('two-factor-auth::otp-form.title'))

@section('content')
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <header class="text-center">
                <h1>{{ trans('two-factor-auth::otp-form.heading') }}</h1>
                <p>{{ trans('two-factor-auth::otp-form.description') }}<p>
            </header>

            {!! Form::open([
                'route'  => 'two-factor-auth.one-time-password.post',
                'method' => 'post',
                'id'     => 'two-factor-auth-one-time-password-post'
            ]) !!}

            @if($errors->has('one_time_password'))
                <div class="alert alert-danger">
                    {{ $errors->first('one_time_password') }}
                </div>
            @endif

            <div class="text-center">
                <div class="form-group">
                    {{ Form::text('one_time_password', null, [
                        'class' => 'form-control',
                        'placeholder' => 'code',
                        'autofocus',
                        'autocomplete' => 'off'
                    ]) }}
                </div>
            </div>

            <button type="submit" class="btn btn-block btn-primary">
                {{ trans('two-factor-auth::otp-form.save') }}
            </button>
            {!! Form::close() !!}
        </div>
    </div>
@endsection